services:
  - type: web
    name: ai-automation
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # (اختياري) لو عندك فهرسة قوالب:
      if [ -f scripts/index_templates.py ]; then python scripts/index_templates.py; fi
    startCommand: uvicorn server.app:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*'
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false              # تحطها بيدك في Render
      - key: BASE_URL
        value: https://ai-automation.onrender.com   # بدّلها بالرابط الحقيقي بعد أول نشر
      - key: WEBHOOK_SECRET
        value: super_secret_32_chars               # غيّرها لقيمة قوية
